### clear table order
DELETE http://localhost:3000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0




### add order
POST http://localhost:3000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0

{
    "userId":3,
    "status":"in consegna",
    "date":"29/05/2024"
}




### update order
PUT http://localhost:3000/order/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0

{
    "status":"annullato"
}




### delete order
DELETE http://localhost:3000/order/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEyMTMxLCJleHAiOjE3MjU3MTM5MzF9.42h_-wYiRzHBMrSm_yzxpwqGBVaCXCsE0Fpwx6CY878
