### clean product
DELETE http://localhost:3000/product/clean
Content-Type: application/json
Authorization: Bearer



### add product
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI1NTYwNDM4LCJleHAiOjE3MjU1NjIyMzh9.s-HTBvLZZMiIDleRuloc7EOaMVhsR_jMNXJ3rUDYRLo

{
    "nameProduct":"forno a microonde",
    "price":10,
    "img":"immagine",
    "category":"elettrodomestici"
}




### update product
PUT http://localhost:3000/product/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI1NTYwNDM4LCJleHAiOjE3MjU1NjIyMzh9.s-HTBvLZZMiIDleRuloc7EOaMVhsR_jMNXJ3rUDYRLo

{
    "nameProduct":"forno a microonde",
    "price":105,
    "img":"immaginee",
    "category":"elettrodomestici"
}


### delete product
DELETE http://localhost:3000/product/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzI1NTYwNDM4LCJleHAiOjE3MjU1NjIyMzh9.s-HTBvLZZMiIDleRuloc7EOaMVhsR_jMNXJ3rUDYRLo
