### clean product
DELETE http://localhost:3000/product/clean
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0



### add product
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0


{
    "nameProduct":"forno a microonde",
    "price":10,
    "img":"immagine",
    "category":"elettrodomestici"
}




### update product
PUT http://localhost:3000/product/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0


{
    "nameProduct":"forno a microonde",
    "price":105,
    "img":"immaginee",
    "category":"elettrodomestici"
}


### delete product
DELETE http://localhost:3000/product/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzI1NzEwMjE2LCJleHAiOjE3MjU3MTIwMTZ9.gEN1RZKZDPXrEKDP7xFvk-5TxW2nWE59vJnauRZfsX0

