###clean auth
DELETE http://localhost:3000/auth/clean
Content-Type: application/json




###clean users
DELETE http://localhost:3000/users/clean
Content-Type: application/json





### register user
POST http://localhost:3000/users
Content-Type: application/json

{
    "username":"antU6jfk",
    "email":"freebossetti@gmail.com",
    "password":"12fgrYss"
}

### register user as admin
POST http://localhost:3000/users/admin
Content-Type: application/json

{
    "username":"antU6jfkhhhh",
    "email":"freeborfssdgetti@gmail.com",
    "password":"1gshTjh7"
}



### update user
PUT http://localhost:3000/users/update/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzI0NTI3NzIzLCJleHAiOjE3MjQ1Mjk1MjN9.DqBogZPAQWQaGb90p8JGezsN7YOf5Dst3KuXopqTZiw



{
    "username":"massimo bossetti2",
    "password":"12345"
}




### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"freebossetti@gmail.com",
    "password":"123456"
}




### logout 
DELETE http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearere yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzI0NTk0MDQ4LCJleHAiOjE3MjQ1OTU4NDh9.EbQZS76tobDn8sryZirjiHe8Pi-X5uZZ4cTc3OF3Oc4





### delete user
DELETE http://localhost:3000/users/7
Content-Type: application/json




### add product
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTcyNDY5NDY1NSwiZXhwIjoxNzI0Njk2NDU1fQ.KvqiN_Jc7z6-xaSCEXmqntH2-SeaFsISS6MVZ9OQcuE

{
    "nameProduct":"porno a microonde",
    "price":10,
    "img":"immagine",
    "category":"elettrodomestici"
}




### update product
PUT http://localhost:3000/product/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTcyNDY5NjczOCwiZXhwIjoxNzI0Njk4NTM4fQ.EPKNAYHhWi-BulHXpQLsTMb9gkTLQdRSsSa3NHUBGho

{
    "nameProduct":"forno a microonde",
    "price":105,
    "img":"immaginee",
    "category":"elettrodomestici"
}


### delete product
DELETE  http://localhost:3000/product/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTcyNDY5NjczOCwiZXhwIjoxNzI0Njk4NTM4fQ.EPKNAYHhWi-BulHXpQLsTMb9gkTLQdRSsSa3NHUBGho



